#spring:
#  application:
#    name: consumer-app
#  kafka:
#    auto-offset-reset: latest
#    bootstrap-servers: localhost:9092
#    group-id: consumer-group
#    topic:
#      name: test-topic
#server:
#  port: 8081


server:
  port: 9191

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

topic: java_topic